FROM node:18.5.0 as builder

WORKDIR /app/storefront

COPY . .

RUN rm -rf node_modules

RUN apt-get update

RUN yarn add sharp

RUN yarn install

RUN npx next build

FROM nginx

EXPOSE 80

COPY --from=builder /app/storefront/public /usr/share/nginx/html

ENTRYPOINT ["nginx", "-g", "daemon off;"]