---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: medusa-storefront
spec:
  replicas: 1
  selector:
    matchLabels:
      name: medusa-storefront
  template:
    metadata:
      labels:
        name: medusa-storefront
    spec:
      containers:
      - name: application
        image: your-dockerhub-account/medusa-storefront
        imagePullPolicy: Always
        envFrom:
        - secretRef:
            name: dockerhub-secret
        ports:
          - containerPort: 3000