---
apiVersion: v1
kind: Service
metadata:
  name: medusa-storefront-service
spec:
  type: LoadBalancer
  ports:
  - name: http
    port: 3000
    targetPort: 3000
  selector:
    name: medusa-storefront